version: "2.4"

services:
  server:
    build:
      context: .
      target: dev
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    environment:
      - TIMEZONE=Europe/Rome
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_DATABASE=phpboilerplate
      - HOSTNAME=http://localhost
    depends_on:
      database:
        condition: service_started

  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=phpboilerplate
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: "mysqladmin -uroot -p${MYSQL_ROOT_PASSWORD:-admin} ping -h localhost"
      timeout: 20s
      retries: 15

volumes:
  dbdata:
